const students =[{
    "id": 1,
    "first_name": "Danette",
    "last_name": "Dictus",
    "email": "ddictus0@delicious.com"
  }, {
    "id": 2,
    "first_name": "Cristina",
    "last_name": "Swaisland",
    "email": "cswaisland1@51.la"
  }, {
    "id": 3,
    "first_name": "Rhea",
    "last_name": "Fliege",
    "email": "rfliege2@jigsy.com"
  }, {
    "id": 4,
    "first_name": "Cloris",
    "last_name": "Casali",
    "email": "ccasali3@amazon.co.jp"
  }, {
    "id": 5,
    "first_name": "Osbourne",
    "last_name": "Goodie",
    "email": "ogoodie4@ebay.com"
  }, {
    "id": 6,
    "first_name": "Garnette",
    "last_name": "Sheering",
    "email": "gsheering5@chron.com"
  }, {
    "id": 7,
    "first_name": "Cobbie",
    "last_name": "Breckwell",
    "email": "cbreckwell6@yolasite.com"
  }, {
    "id": 8,
    "first_name": "Bertha",
    "last_name": "Chataignier",
    "email": "bchataignier7@com.com"
  }, {
    "id": 9,
    "first_name": "Marv",
    "last_name": "Fantini",
    "email": "mfantini8@wufoo.com"
  }, {
    "id": 10,
    "first_name": "Janelle",
    "last_name": "Tabbernor",
    "email": "jtabbernor9@nytimes.com"
  }]

module.exports=students;
